name: Build
permissions:
  contents: read
on: [push, pull_request, workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun i --frozen-lockfile --ignore-scripts
      - run: bun run build
